// JS/08. Angular/Project/client/src/app/user/register/register.component.ts
import { Component } from '@angular/core';
import { AutoFocusDirective } from '../../directives/auto-focus.directive';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [AutoFocusDirective, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {

}

<div class="wrapper">
    <form class="registerForm">
        <fieldset>
            <legend>Register</legend>

            <p class="field">
                <label for="username">Username</label>
                <input type="username" name="username" id="username" required appAutoFocus>
            </p>

            <p class="field">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" required>
            </p>

            <p class="field">
                <label for="contact">Contact number</label>
                <input type="contact" name="contact" id="contact" required>
            </p>

            <p class="field">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
            </p>

            <p class="field">
                <label for="rePass">Repeat Password</label>
                <input type="rePass" name="rePass" id="rePass" required>
            </p>

            <p>Already a member? Click <span><a routerLink='/login'>here</a></span> to log in!</p>

            <input type="submit" value="Register">

        </fieldset>
    </form>
</div>

// JS/06. React JS/Project/client/src/components/register/Register.jsx
import { Link } from "react-router-dom";

export default function Register() {
    return (
        <section id="register-page" className="content auth">
            <form id="register">
                <div className="container">
                    <img src="home-logo2.png" alt="Home" className='brand-logo' />
                    <h1>Register</h1>

                    <label htmlFor="username">Username:</label>
                    <input type="text" id="username" name="username" placeholder="username" />

                    <label htmlFor="email">Email:</label>
                    <input type="email" id="email" name="email" placeholder="maria@email.com" />

                    <label htmlFor="pass">Password:</label>
                    <input type="password" name="password" id="register-password" />

                    <label htmlFor="repass">Repeat Password:</label>
                    <input type="password" name="repeat-password" id="repeat-password" />

                    <input className="btn submit" type="submit" value="Register" />

                    <p className="field">
                        <span>Already a member? Click <Link to="/login">here</Link> to log back in!</span>
                    </p>
                </div>
            </form>
        </section>
    );
}
