// JS/08. Angular/Project/client/src/app/core/header/header.component.ts
import { Component } from '@angular/core';
import { FooterComponent } from "../footer/footer.component";
import { RouterLink } from '@angular/router';
import { UserService } from '../../user/user.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

  constructor(private userService: UserService) { }

  logout() {
    this.userService.logout();
  }
}

<header>
    <div class="logo-wrapper">
        <img src="magic-shop-logo.png" />
        <p class="logo"><span class="logo">Magic item shop</span></p>
    </div>
    <div class="navbar-wrapper">
        <nav>
            <ul>
                <li>
                    <a routerLink="/home">Home</a>
                </li>
                <li>
                    <a routerLink="/catalog">Catalog</a>
                </li>
                <li>
                    <a routerLink="/register">Register</a>
                </li>
                <li>
                    <a routerLink="/login">Login</a>
                </li>
                <li>
                    <a routerLink="/create">List an item</a>
                </li>
                <li>
                    <a (click)="logout()" routerLink="#">Logout</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="logo-wrapper">
        <a routerLink="/profile"><span>Profile</span></a>
        <img src="profile-logo.png" />
    </div>
</header>

// JS/06. React JS/Project/client/src/components/header/Header.jsx
import { NavLink } from 'react-router-dom';
import './Header.css'

export default function Header() {
    const navigation = [
        // { name: 'Home', href: '/' },
        { name: 'Book of the Week', href: '/book-of-the-week' },
        { name: 'Catalog', href: '/catalog' },
        { name: 'Create', href: '/create' },
        { name: 'Top 5 List', href: '/top-five-list' },
        { name: 'Register', href: '/register' },
        { name: 'Login', href: '/login' },
        // { name: 'Profile', href: '/profile' },
        { name: 'Logout', href: '/logout' },
        { name: 'About', href: '/about' },
    ]

    return (
        <header>
            <nav>
                <div>
                    <NavLink to="/" id="home-logo">
                        <img src="home-logo.jpg" alt="Home" className='home-logo' />
                    </NavLink>
                </div>
                <ul>
                    {navigation.map((item) => (
                        <li key={item.name}>
                            <NavLink
                                to={item.href}
                            >
                                {item.name}
                            </NavLink>
                        </li>
                    ))}
                </ul>
                <div>
                    <NavLink to="/profile" id="profile-logo">
                        <img src="profile-logo.jpg" alt="Profile" className='profile-logo' />
                    </NavLink>
                </div>
            </nav>
        </header>
    );
}
